[env]
RUST_LOG = 'debug'

[tasks.build]
run = 'cargo build'
alias = 'b'

[tasks.build-release]
run = 'cargo build --release'
alias = 'br'

[tasks.test]
run = 'cargo test'
alias = 't'

[tasks.test-release]
run = 'cargo test --release'
alias = 'tr'

[tasks.run-daemon]
run = 'cargo run --bin wgpaper-daemon-http'
alias = 'rd'

[tasks.run-daemon-release]
run = 'cargo run --bin wgpaper-daemon-http --release'
alias = 'rdr'

[tasks.run-daemon-sway]
usage = '''
arg "<output_count>" default="1"
'''
run = 'WGPAPER_PROJECT_COMMAND="mise rd" WLR_WL_OUTPUTS=${usage_output_count} sway -c sway-config.sh'
alias = 'rds'

[tasks.run-daemon-sway-release]
usage = '''
arg "<output_count>" default="1"
'''
run = 'WGPAPER_PROJECT_COMMAND="mise rdr" WLR_WL_OUTPUTS=${usage_output_count} sway -c sway-config.sh'
alias = 'rdsr'

[tasks.run-systemd]
usage = '''
arg "<unit_name>"
arg "<command>" var=#true
'''
run = 'systemctl --user reset-failed ${usage_unit_name} || true; systemd-run --user -d -E WAYLAND_DISPLAY=$WAYLAND_DISPLAY -p SyslogIdentifier=${usage_unit_name} -u ${usage_unit_name} ${usage_command}'
alias = 'rs'

[tasks.systemd-logs]
usage = '''
arg "<unit_name>"
'''
run = 'journalctl --user -t ${usage_unit_name}'
alias = 'sl'

[tasks.status-systemd]
usage = '''
arg "<unit_name>"
'''
run = 'systemctl --user status ${usage_unit_name}'
alias = 'sts'

[tasks.stop-systemd]
usage = '''
arg "<unit_name>"
'''
run = 'systemctl --user stop ${usage_unit_name}'
alias = 'ss'

[tasks.run-systemd-daemon]
usage = '''
arg "<unit_name>" default="wgpaper-rd"
'''
run = 'mise rs ${usage_unit_name} mise rd'
alias = 'rsd'

[tasks.systemd-daemon-logs]
usage = '''
arg "<unit_name>" default="wgpaper-rd"
'''
run = 'mise sl ${usage_unit_name}'
alias = 'sdl'

[tasks.status-systemd-daemon]
usage = '''
arg "<unit_name>" default="wgpaper-rd"
'''
run = 'mise sts ${usage_unit_name}'
alias = 'stsd'

[tasks.stop-systemd-daemon]
usage = '''
arg "<unit_name>" default="wgpaper-rd"
'''
run = 'mise ss ${usage_unit_name}'
alias = 'ssd'

[tasks.run-systemd-daemon-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdr"
'''
run = 'mise rs ${usage_unit_name} mise rdr'
alias = 'rsdr'

[tasks.systemd-daemon-logs-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdr"
'''
run = 'mise sl ${usage_unit_name}'
alias = 'sdlr'

[tasks.status-systemd-daemon-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdr"
'''
run = 'mise sts ${usage_unit_name}'
alias = 'stsdr'

[tasks.stop-systemd-daemon-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdr"
'''
run = 'mise ss ${usage_unit_name}'
alias = 'ssdr'

[tasks.run-systemd-daemon-sway]
usage = '''
arg "<output_count>" default="1"
arg "<unit_name>" default="wgpaper-rds"
'''
run = 'mise rs ${usage_unit_name} mise rds ${usage_output_count}'
alias = 'rsds'

[tasks.systemd-daemon-sway-logs]
usage = '''
arg "<unit_name>" default="wgpaper-rds"
'''
run = 'mise sl ${usage_unit_name}'
alias = 'sdsl'

[tasks.status-systemd-daemon-sway]
usage = '''
arg "<unit_name>" default="wgpaper-rds"
'''
run = 'mise sts ${usage_unit_name}'
alias = 'stsds'

[tasks.stop-systemd-daemon-sway]
usage = '''
arg "<unit_name>" default="wgpaper-rds"
'''
run = 'mise ss ${usage_unit_name}'
alias = 'ssds'

[tasks.run-systemd-daemon-sway-release]
usage = '''
arg "<output_count>" default="1"
arg "<unit_name>" default="wgpaper-rdsr"
'''
run = 'mise rs ${usage_unit_name} mise rdsr ${usage_output_count}'
alias = 'rsdsr'

[tasks.systemd-daemon-sway-logs-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdsr"
'''
run = 'mise sl ${usage_unit_name}'
alias = 'sdslr'

[tasks.status-systemd-daemon-sway-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdsr"
'''
run = 'mise sts ${usage_unit_name}'
alias = 'stsdsr'

[tasks.stop-systemd-daemon-sway-release]
usage = '''
arg "<unit_name>" default="wgpaper-rdsr"
'''
run = 'mise ss ${usage_unit_name}'
alias = 'ssdsr'

[tasks.fmt]
run = 'cargo fmt'
alias = 'f'

[tasks.clippy]
run = 'cargo clippy'
alias = 'c'

[tasks.clippy-fix]
run = 'cargo clippy --fix'
alias = 'cf'

[tasks.clippy-fix-dirty]
run = 'cargo clippy --fix --allow-dirty'
alias = 'cfd'
