[package]
name = "wgpaper-config"
version = "0.1.0"
edition = "2024"

[dependencies]
csscolorparser = { workspace = true }
anyhow = { workspace = true }
const_format = { workspace = true }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum = "0.27.2"
strum_macros = "0.27.2"
shellexpand = "3.1.1"
