[package]
name = "wgpaper-daemon-http"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
calloop = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

lib-wgpaper-daemon = { path = "../lib-wgpaper-daemon" }
wgpaper-config = { path = "../wgpaper-config" }
actix-web = "4.12.1"
